CREATE TABLE IF NOT EXISTS animal (
    id_animal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especie_classe VARCHAR(50) NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    data_nascimento DATE,
    id_cliente INTEGER NOT NULL,

    CONSTRAINT fk_animal_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
);