CREATE TABLE IF NOT EXISTS atendente (
    id_atendente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL UNIQUE,

    CONSTRAINT fk_atendente_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
);