CREATE TABLE IF NOT EXISTS atendimento (
    id_atendimento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    descricao VARCHAR(255),
    id_cliente INTEGER NOT NULL,
    id_animal INTEGER NOT NULL,
    id_veterinario INTEGER NOT NULL,
    id_atendente INTEGER NOT NULL,

    CONSTRAINT fk_atendimento_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente),

    CONSTRAINT fk_atendimento_animal
        FOREIGN KEY (id_animal)
        REFERENCES animal(id_animal),

    CONSTRAINT fk_atendimento_veterinario
        FOREIGN KEY (id_veterinario)
        REFERENCES veterinario(id_veterinario),

    CONSTRAINT fk_atendimento_atendente
        FOREIGN KEY (id_atendente)
        REFERENCES atendente(id_atendente)
); 